### ISSUE TITLE
blank black page on run

### ISSUE THREAD

**Issue by dylankolson** [wbg-bigdata/nightlights#49]
I get this error in the javascript window

TypeError: reference.layer.type.values.forEach is not a function

page is just black when it loads with default api

**Comment by DylanMoriarty** [comment]
This seems to be due to the Mapbox GL node module. We're currently using version `0.11.2`, which throws the error

```
Uncaught TypeError: reference.layer.type.values.forEach is not a function
    at Object.require.77.../util/util (vendor.js:11886)
    at s (vendor.js:1)
```


and... updating the version to `0.13.0` & above will let the site _mostly_ draw, but still errors and out yeilds 

```
Uncaught TypeError: Classes[(refLayer || layer).type] is not a constructor
    at Function.StyleLayer.create (http://localhost:9000/scripts/vendor.js:12076:12)
    at Object.addLayer (http://localhost:9000/scripts/vendor.js:11847:32)...
```

Will need to fix this before building the site again.

**Comment by dereklieu** [comment]
The version of GL that's currently running on the site, `v0.11.2`, is many breaking changes behind what's current. Since the dependencies here aren't locked, it's probably unlikely we'll be able to re-build a working version using the current code (and probably not a worthwhile endeavor).

There are a few things to do to correct this.

- [ ] Upgrade mapbox gl-related dependencies.
- [ ] Port the parts of the map code using old API, ie. [`Map#batch`](https://github.com/wbg-bigdata/nightlights/blob/develop/app/scripts/component/light-map.js#L194).
- [ ] Make sure the tilesets are being served by the current `v4` endpoint.
- [ ] Lock the dependencies, either switching dependency management to yarn or using `npm shrinkwrap`.

**Comment by RameshByndoor** [comment]
Facing same issue mentioned by DylanMoriarty

**Comment by dereklieu** [comment]
@RameshByndoor what browser and operating system?

Noting that although the site loads a *really* old version of Mapbox GL, it still runs on recent versions of Chrome, FF, and Safari, per my testing.
